- hosts: localhost
  connection: local
  pre_tasks:
    - name: Verify OS
      ansible.builtin.fail:
        msg: Only Ubuntu 22.04 is supported for this branch. Please refer to https://autowarefoundation.github.io/autoware-documentation/main/installation/autoware/source-installation/.
      when: ansible_distribution_version != '22.04'

    - name: Print args
      ansible.builtin.debug:
        msg:
          - module: "{{ module }}"
          - rosdistro: "{{ rosdistro }}"
          - rmw_implementation: "{{ rmw_implementation }}"
          - cuda_version: "{{ cuda_version }}"
          - cudnn_version: "{{ cudnn_version }}"
          - tensorrt_version: "{{ tensorrt_version }}"
  roles:
    # Autoware Universe base dependencies
    - role: autoware.dev_env.rmw_implementation
      when: module == 'base' or module == 'all'
    - role: autoware.dev_env.plotjuggler
      when: module == 'developer'
    - role: autoware.dev_env.pre_commit
      when: module == 'developer'
    - role: autoware.dev_env.ros2_dev_tools
      when: module == 'developer'
    - role: autoware.dev_env.git_lfs
      when: module == 'developer'

    # Module specific dependencies
    - role: autoware.dev_env.geographiclib
      when: module == 'main-perception' or module == 'all'
    - role: autoware.dev_env.cuda
      when: module == 'main-perception' or module == 'all'
    - role: autoware.dev_env.tensorrt
      when: module == 'main-perception' or module == 'all'
    - role: autoware.dev_env.pacmod
      when: module == 'planning-control' or module == 'main-perception' or module == 'all'
